version: '3'
services:
  database:
    image: postgres # use latest official postgres version
    restart: always
    env_file:
      - database.env # configure postgres
    # volumes:
    #   - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    container_name: safe-cash-service_postgres
    ports:
      - 5432:5432

  server:
    # build:
    image: safe-cash-service
    restart: always
    # container_name: cinema-admin_app
    environment:
      - POSTGREST_DB_HOST=database
      - POSTGREST_DB_PORT=5432
      - POSTGREST_DB_USER=user
      - POSTGREST_DB_PASSWORD=123456
      - POSTGREST_DB_NAME=safe_smart_cash
    # # volumes:
    container_name: safe-cash-service_server
    links:
      - database
    depends_on:
      - database

    ports:
      - "6000:6000"
  
networks:
  backend:
    driver: "bridge"