version: '3'
services:
  server:
    image: safe-cash-service
    restart: always
    # container_name: cinema-admin_app
    # environment:
    #   - POSTGREST_DB_HOST=database
    #   - POSTGREST_DB_PORT=5432
    #   - POSTGREST_DB_USER=user
    #   - POSTGREST_DB_PASSWORD=123456
    #   - POSTGREST_DB_NAME=cinema-admin
    # # volumes:
    container_name: safe-cash-service_server

    ports:
      - "6000:6000"
